--1
CREATE DATABASE PERSONNET

--2
USE PERSONNET

--3
CREATE TABLE TB_User (

IdUser INTEGER NOT NULL IDENTITY PRIMARY KEY,
Name VARCHAR(128) NOT NULL,
E_mail VARCHAR(128) UNIQUE NOT NULL,
Pass VARCHAR(512) NOT NULL,
DirProfilePhoto VARCHAR(64),
BirthDate DATE NOT NULL,
LastAccess DATETIME,
HasPremiumAccess BIT NOT NULL

)

CREATE TABLE TB_Content (

IdContent INTEGER NOT NULL IDENTITY PRIMARY KEY,
ContentType VARCHAR(8) NOT NULL,
UploadDate DATETIME NOT NULL,
ContentViews INTEGER NOT NULL,
IdUser INTEGER NOT NULL REFERENCES TB_User(IdUser)

)

CREATE TABLE TB_Text (

IdContent INTEGER NOT NULL PRIMARY KEY REFERENCES TB_Content(IdContent),
ContentText TEXT,
Title VARCHAR(256) NOT NULL

)

CREATE TABLE TB_Photo (

IdContent INTEGER NOT NULL PRIMARY KEY REFERENCES TB_Content(IdContent),
DirPhoto TEXT NOT NULL,
Title VARCHAR(256) NOT NULL

)

CREATE TABLE TB_Video (

IdContent INTEGER NOT NULL PRIMARY KEY REFERENCES TB_Content(IdContent),
DirVideo TEXT NOT NULL,
Title VARCHAR(256) NOT NULL

)

CREATE TABLE Content_Access_Denial (

IdAccessDenial INTEGER NOT NULL IDENTITY PRIMARY KEY,
IdUser INTEGER NOT NULL REFERENCES TB_User(IdUser),
IdContent INTEGER NOT NULL REFERENCES TB_Content(IdContent)

)

CREATE TABLE TB_Admin (

IdAdmin INTEGER NOT NULL IDENTITY PRIMARY KEY,
Name VARCHAR(128) NOT NULL,
E_mail VARCHAR(128) UNIQUE NOT NULL,
Pass VARCHAR(512) NOT NULL,
CurrentStatus VARCHAR(16),
LastAccess DATETIME

)

CREATE TABLE TB_Notification (

IdNotification INTEGER NOT NULL IDENTITY PRIMARY KEY,
Content VARCHAR(512)

)

CREATE TABLE TB_UserNotification (

IdNotification INTEGER NOT NULL PRIMARY KEY REFERENCES TB_Notification(IdNotification),
IdUser INTEGER NOT NULL REFERENCES TB_User(IdUser)

)

CREATE TABLE TB_AdminNotification (

IdNotification INTEGER NOT NULL PRIMARY KEY REFERENCES TB_Notification(IdNotification),
IdAdmin INTEGER NOT NULL REFERENCES TB_Admin(IdAdmin)

)

CREATE TABLE TB_Core (

IdCore INTEGER NOT NULL IDENTITY PRIMARY KEY,
Name VARCHAR(128) NOT NULL,
Description VARCHAR(512),
IdUser INTEGER NOT NULL REFERENCES TB_User(IdUser)

)

CREATE TABLE Assoc_Core_Content (

IdAssoc INTEGER NOT NULL IDENTITY PRIMARY KEY,
IdCore INTEGER NOT NULL REFERENCES TB_Core(IdCore),
IdContent INTEGER NOT NULL REFERENCES TB_Content(IdContent)

)

CREATE TABLE Core_Access_Denial (

IdAccessDenial INTEGER NOT NULL IDENTITY PRIMARY KEY,
IdUser INTEGER NOT NULL REFERENCES TB_User(IdUser),
IdCore INTEGER NOT NULL REFERENCES TB_Core(IdCore)

)

CREATE TABLE TB_AdditionalData (

IdAdditionalData INTEGER NOT NULL IDENTITY PRIMARY KEY,
DataType VARCHAR(32),
DataContent VARCHAR(128)

)

CREATE TABLE TB_UserAdditionalData (

IdAdditionalData INTEGER NOT NULL PRIMARY KEY REFERENCES TB_AdditionalData(IdAdditionalData),
IdUser INTEGER NOT NULL REFERENCES TB_User(IdUser)

)

CREATE TABLE TB_CoreAdditionalData (

IdAdditionalData INTEGER NOT NULL PRIMARY KEY REFERENCES TB_AdditionalData(IdAdditionalData),
IdCore INTEGER NOT NULL REFERENCES TB_Core(IdCore)

)

CREATE TABLE TB_Keyword (

IdKeyword INTEGER NOT NULL IDENTITY PRIMARY KEY,
IdCore INTEGER NOT NULL REFERENCES TB_Core(IdCore),
KeywordContent VARCHAR(32)

)

CREATE TABLE TB_Genre (

IdGenre INTEGER NOT NULL IDENTITY PRIMARY KEY,
IdCore INTEGER NOT NULL REFERENCES TB_Core(IdCore),
GenreContent VARCHAR(32)

)