//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Admin()
        {
            this.TB_Notification = new HashSet<TB_Notification>();
        }
    
        public int IdAdmin { get; set; }
        public string Name { get; set; }
        public string E_mail { get; set; }
        public string Pass { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Notification> TB_Notification { get; set; }
    }
}
