//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Content()
        {
            this.Assoc_Core_Content = new HashSet<Assoc_Core_Content>();
            this.Content_Access_Denial = new HashSet<Content_Access_Denial>();
        }
    
        public int IdContent { get; set; }
        public string ContentType { get; set; }
        public System.DateTime UploadDate { get; set; }
        public int ContentViews { get; set; }
        public int IdUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assoc_Core_Content> Assoc_Core_Content { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content_Access_Denial> Content_Access_Denial { get; set; }
        public virtual TB_User TB_User { get; set; }
        public virtual TB_Photo TB_Photo { get; set; }
        public virtual TB_Text TB_Text { get; set; }
        public virtual TB_Video TB_Video { get; set; }
    }
}
