//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Notification
    {
        public int IdNotification { get; set; }
        public string Content { get; set; }
    
        public virtual TB_Admin TB_Admin { get; set; }
        public virtual TB_User TB_User { get; set; }
    }
}
