//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TB_Text
    {
        [Display(Name="Post")]
        public int IdContent { get; set; }
        [Display(Name="Texto")]
        [Required(ErrorMessage = "O texto é obrigatório.")]
        public string ContentText { get; set; }
        [Display(Name = "Título")]
        [Required(ErrorMessage = "O título é obrigatório.")]
        [MaxLength(256, ErrorMessage = "O título deve possuir até 256 caracteres.")]
        public string Title { get; set; }

        public virtual TB_Content TB_Content { get; set; }
    }
}
