//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_User()
        {
            this.Content_Access_Denial = new HashSet<Content_Access_Denial>();
            this.Core_Access_Denial = new HashSet<Core_Access_Denial>();
            this.TB_Content = new HashSet<TB_Content>();
            this.TB_Core = new HashSet<TB_Core>();
            this.TB_AdditionalData = new HashSet<TB_AdditionalData>();
            this.TB_Notification = new HashSet<TB_Notification>();
        }
    
        public int IdUser { get; set; }
        public string Name { get; set; }
        public string E_mail { get; set; }
        public string Pass { get; set; }
        public string DirProfilePhoto { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
        public bool HasPremiumAccess { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content_Access_Denial> Content_Access_Denial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Core_Access_Denial> Core_Access_Denial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Content> TB_Content { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Core> TB_Core { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_AdditionalData> TB_AdditionalData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Notification> TB_Notification { get; set; }
    }
}
